### ISSUE TITLE
Suggestion: Use Sound ID instead of names

### ISSUE THREAD

**Issue by robuuuste** [petertalbanese/SoundSwapper#1]
Hi, awesome plugin! I have a suggestion though. Would it be possible to use Sound IDs instead of the names provided on the wiki page? The list on the wiki page is a bit outdated and doesn't contain sounds from more recent updates. For example, Tumeken's Shadow attack sound has Sound ID 6410, while the wiki list only goes up to ID 4996. Using the Visual Sounds plugin you can quite easily find out the Sound ID of the sound you wish to swap. For example, you could put "6410.wav" in the SoundSwapper folder and add 6410 to the list in the plugin.

**Comment by petertalbanese** [comment]
Hey! I would definitely consider changing that. I decided to go with names as I thought it would be easier to track what you've changed. I also didn't know about the Visual Sounds plugin for finding sound ids! With that in mind I could definitely switch it over.

**Comment by petertalbanese** [comment]
PR is up and waiting for approval!
