### ISSUE TITLE
Doesnt work

### ISSUE THREAD

**Issue by EliJ91** [petertalbanese/SoundSwapper#13]
Swapping sounds simply doesnt work but "Consume Sounds Effects" does mute all audio.

**Comment by EliJ91** [comment]
Ive added the sound to the SoundSwapper folder and it still doesnt work.

**Comment by EliJ91** [comment]
Restarting the client makes it work

**Comment by petertalbanese** [comment]
Hey sorry! Did you figure out what was happening? In general, if you add the sounds to the folder *after* adding the sound ids to your list, it won't update right away. You need to make a change in the list or reload the plugin for it to reload the sounds.
