### ISSUE TITLE
freezing

### ISSUE THREAD

**Issue by Zoltus** [petertalbanese/SoundSwapper#2]
game freezes for second sometimes when using the plugin, after disabling i didnt have the freezing problems

**Comment by petertalbanese** [comment]
Odd, I'll have to look into this. I'm thinking about changing to having the user provide sound ids directly, rather than using the name of the sound. It'll remove a big lookup for the sound id in code, so it may resolve the freezing issue.

**Comment by Zoltus** [comment]
> Odd, I'll have to look into this. I'm thinking about changing to having the user provide sound ids directly, rather than using the name of the sound. It'll remove a big lookup for the sound id in code, so it may resolve the freezing issue.

Ye i checked the code and it finds the sound from 5k sounds every sound the game plays. 
You could do smthing like 
config takes array like 10=40,1=5,2=6
meaning id 10 is replaced with 40, 1 with 5 ect then there wouldnt be that huge check every sound. 
and anyways my self i prefer sound ids. I might fork it and pullrequest later this week if i have time or u havent done it yet but will see.
