### ISSUE TITLE
Area Sounds Swap

### ISSUE THREAD

**Issue by cmsu224** [petertalbanese/SoundSwapper#5]
This only works with Sound Effects and not Area sounds, right?  It'd be great if you could swap the sounds for both.  I believe the method for getting those is _**onAreaSoundEffectPlayed**_.

**Comment by petertalbanese** [comment]
Sure I can definitely look into this! Yes this is only covering _onSoundEffectPlayed()_ right now. Currently working on a bug where there is some lag when a lot of sounds are playing quickly, so I want to get that resolved before adding more load on though. It may be better to do that as a separate plugin, but I'll check how well things run.

**Comment by Zaino60** [comment]
hey, any update on this? Would love to be able to replace area sounds too!

**Comment by petertalbanese** [comment]
Sorry for the delay on this :( I've been swamped at work, so we still haven't totally patched up the performance issues on the original plugin just yet. I personally don't see the issues on my machine, so I can test this out to see how it runs on my rig, but I assume it will make performance even worse for those who weren't doing too well with the original 😅

**Comment by petertalbanese** [comment]
Decided to make each of these a toggle so that you can choose to swap sounds/area sounds/both. This way people won't have performance issues if they just want 1 or the other 😄 Will toss up a quick pr tonight.

Edit: PR is up!
