### ISSUE TITLE
Doest seem to work.

### ISSUE THREAD

**Issue by EliJ91** [petertalbanese/SoundSwapper#6]
Ive tried changing the drop sound but it just mutes it. I followed the instructions clearly. No idea

**Comment by jacobholden** [comment]
@EliJ91 I had the same problem so I took a look at the src code, you need to create a folder called "SoundSwapper" in your runelite's root directory, and place the sound inside there.

**Comment by petertalbanese** [comment]
Sorry about that! I'll update the Readme with the newer instructions. I thought I had it automatically create the folder when you activate the plugin. If not I'll go in and change that too.

**Comment by petertalbanese** [comment]
Hey, I was making some changes in the code and just wanted to update on this. On Plugin startup it should be creating the directory. I have a `SOUND_DIR.mkdir();` line in my `startUp()` function. Not sure why it wasn't automatically created for you so I might have to fiddle with this a bit on my end.

**Comment by EliJ91** [comment]
I placed the file in the SoundSwapper folder and it still doesnt work
